### ISSUE TITLE
Carla xorg-server dep

### ISSUE THREAD

**Issue by kopr12** [yemouu/moulay#1]
Hi, using Wayland here and I don't really have all the `xorg-* stuff`, when I tried to emerge Carla it wanted me to install a bunch of xorg deps, when I tried to set -X the `juce` USE flag was a problem then because it's set under `X?` in the ebuild. Anyway I made it to work by deleting `x11-base/xorg-server` line , but you can maybe just move `juce` out of `X?` loop, that would work as well or just drop `xorg-server` line, you don't need it actually, it can only cause problems and people who do run `xorg-server` would already have it installed before they try to emerge Carla.

**Comment by yemouu** [comment]
I have removed `x11-base/xorg-server` as a dependency and replaced it with `x11-libs/libX11` and `x11-base/xorg-proto` so the package shouldn't be installing unnecessary xorg packages now.

Regarding the useflags, Carla's build system will only build with juce if x11 libraries are found so i think that the `juce` useflag should still depend on the `X` useflag

**Comment by kopr12** [comment]
Seems good, thanks!
