### ISSUE TITLE
helix-9999 no longer builds

### ISSUE THREAD

**Issue by univerz** [yemouu/moulay#2]
error:
```
 * Applying helix-0.5.0-helix-core_src_lib.patch ...
patching file helix-core/src/lib.rs
Hunk #1 FAILED at 73.
1 out of 1 hunk FAILED -- saving rejects to file helix-core/src/lib.rs.rej                                                                                                                                   [ !! ]
 * ERROR: app-editors/helix-9999::moulay failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/app-editors/helix-9999/files/helix-0.5.0-helix-core_src_lib.patch
```

**Comment by yemouu** [comment]
Sorry for the late response, I've just updated the ebuild so it should compile just fine now

**Comment by univerz** [comment]
thank you :). one problem remains:

```fatal: unable to access 'https://github.com/omertuc/tree-sitter-go-work/': Could not resolve host: github.com```

after quick googling it looks like it's not possible to download sources at this stage. not sure how to hack around it.

**Comment by yemouu** [comment]
I'm not sure what the issue is, i've cleared my distfiles and was able to compile both 22.03 and 9999.
I don't see anywhere in the ebuild where that link would be getting accessed, have you updated the repo?

**Comment by univerz** [comment]
> I don't see anywhere in the ebuild where that link would be getting accessed, have you updated the repo?

it's called from `helix-term/build.rs` - `fetch_grammars()` == [building tree-sitter grammars](https://github.com/helix-editor/helix#installation).

network should not be accessible outside of `src_unpack` stage according to [this](https://groups.google.com/a/chromium.org/g/chromium-os-dev/c/muV3a7KSS1E/m/9u3MIheHAgAJ).

but if it works for you, i will try again after full emerge world, my gentoo is slightly out of date.

**Comment by yemouu** [comment]
looking at `helix-term/build.rs`, setting `HELIX_DISABLE_AUTO_GRAMMAR_BUILD=1` as an environment variable should fix this.
ill add it to the ebuild shortly

im not sure why im not running into this

**Comment by univerz** [comment]
> im not sure why im not running into this

maybe you have [`FEATURES="-network-sandbox"`](https://www.reddit.com/r/Gentoo/comments/c06b56/networksandbox_causing_build_issues/) set globally?

> looking at `helix-term/build.rs`, setting `HELIX_DISABLE_AUTO_GRAMMAR_BUILD=1` as an environment variable should fix this. ill add it to the ebuild shortly

works, but without grammars step. it should be possible to reuse `helix-loader/src/main.rs` for download step & then patch `helix-term` to skip `fetch_grammars`, but as a quick hack this builds:

```diff --git a/app-editors/helix/helix-9999.ebuild b/app-editors/helix/helix-9999.ebuild
index 625526c..9de695a 100644
--- a/app-editors/helix/helix-9999.ebuild
+++ b/app-editors/helix/helix-9999.ebuild
@@ -10,6 +10,7 @@ inherit cargo
 
 DESCRIPTION="A post-modern modal text editor"
 HOMEPAGE="https://helix-editor.com/"
+RESTRICT=network-sandbox
 
 if [[ ${PV} == 9999 ]]
 then
@@ -32,7 +33,6 @@ LICENSE="MPL-2.0"
 SLOT="0"
 
 src_compile() {
-       export HELIX_DISABLE_AUTO_GRAMMAR_BUILD=1
        cargo_src_compile
 }
```

but i can't find that `runtime` directory on filesystem after install - there should be themes etc & user should link to it.

**Comment by yemouu** [comment]
the grammars step can be done after install with `hx -g fetch && hx -g build` which is what i was intending the user to do.

as for the rest of the runtime dir stuff, i didn't realize it was necessary for other parts helix so i've included it in the ebuild install now as well as some post install instructions
